### ISSUE TITLE
All contextRoot filename.

### ISSUE THREAD

**Issue by bedrich** [matthewwithanm/grunt-jinja#1]
Hi @matthewwithanm I was trying to set up a single JSON as the context for all my templates, and created an `all.json` file as directed. However, the templates were not picking up the context. I did some poking around and it looks like the grunt task calls  `loadContext('_all')`. I changed the filename to `_all.json` and voila! 

Thanks for writing this task, good stuff!

**Comment by matthewwithanm** [comment]
Thanks, @bedrich! I see where the misunderstanding is. The underscores are in the README but, because it's markdown, they're just making the text italic! I'll escape them. Thanks for the heads up!

**Comment by paulmsmith** [comment]
How do I access the context in the templates? 

```
{{ context.key }} 
```

Doesn't seem to be working?

**Comment by matthewwithanm** [comment]
`{{ key }}`?

**Comment by paulmsmith** [comment]
Thanks @matthewwithanm. I found it in the end. Just assumed it would arrive in one big object.

**Comment by matthewwithanm** [comment]
:thumbsup:
